[package]
name = "tool_derive"
version = "0.1.0"
authors = ["cpdt <copodt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full", "extra-traits"] }
quote = "0.6"
proc-macro2 = "0.4"
